config/routes.rb
Rails.application.routes.draw do
  root to: "feed#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :posts, only: [ :index, :show, :new ]
  resources :projects, only: [ :index, :show ]

  namespace :admin do
    root to: "dashboard#index" # Admin 대시보드 (선택 사항)
    resources :members
    resources :projects, only: [ :index ]
    resources :posts, only: [ :index ]
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html data-theme="lemonade" class="h-full">
  <head>
    <title><%= content_for(:title) || "dg admin" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-full text-slate-700 bg-gray-100">
    <header class="flex-shrink-0 p-4 bg-white border-b border-gray-300 flex justify-between items-center">
      <a href="/admin" class="text-xl font-bold">고래밥 블로그 관리</a>
      <a href="/">홈으로 이동</a>
    </header>
    <main class="flex-grow flex overflow-hidden">
      <aside class="flex-shrink-0 w-64 p-4 bg-white border-r border-gray-300">
        <nav>
          <ul class="flex flex-col gap-2">
            <li class="<%= current_page?(admin_root_path) ? 'bg-blue-500 text-white' : 'bg-gray-300' %> text-center rounded-lg transition-colors">
              <%= link_to "대시보드", admin_root_path, class: "block w-full h-full p-3" %>
            </li>
            
            <li class="<%= current_page?(admin_members_path) || controller_name == 'members' ? 'bg-blue-500 text-white' : 'bg-gray-300' %> text-center rounded-lg transition-colors">
              <%= link_to "멤버", admin_members_path, class: "block w-full h-full p-3" %>
            </li>
            
            <li class="<%= current_page?(admin_posts_path) || controller_name == 'posts' ? 'bg-blue-500 text-white' : 'bg-gray-300' %> text-center rounded-lg transition-colors">
              <%= link_to "포스트", admin_posts_path, class: "block w-full h-full p-3" %>
            </li>
            
            <li class="<%= current_page?(admin_projects_path) || controller_name == 'projects' ? 'bg-blue-500 text-white' : 'bg-gray-300' %> text-center rounded-lg transition-colors">
              <%= link_to "프로젝트", admin_projects_path, class: "block w-full h-full p-3" %>
            </li>
          </ul>
        </nav>
      </aside>
      <section class="w-full p-4">
        <%= yield %>
      </section>
    </main>

    <!-- 모달이 여기 로드될 자리 -->
    <turbo-frame id="modal"></turbo-frame>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="lemonade" class="h-full">
  <head>
    <title><%= content_for(:title) || "dev.goraebap" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-full text-slate-700">    
    <%= render 'shared/header' %>
    <main class="flex-grow overflow-hidden">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>